services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile

    volumes:
      - ./:/root/src

    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  db:
    image: mongo:latest
    ports:
      - 27017:27017

    env_file:
      - .env
